services:
  - type: worker
    name: telegram-forward-bot
    env: python
    plan: starter
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: API_ID
        value: your_api_id
      - key: API_HASH
        value: your_api_hash
      - key: BOT_TOKEN
        value: your_bot_token
      - key: DEST_CHANNEL
        value: -100xxxxxxxxxx  # your destination channel ID
